[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
ignored_error_codes = [2519,2018,5574,6321,8261]
fs_permissions = [
    { access = "read", path = "./script/templates/" },
    { access = "read-write", path = "./test/helpers/deployers/" }
]

# Dependencies are managed via git submodules at fixed commits:
# - lib/openzeppelin-contracts: v5.3.0 (e4f70216d759d8e6a64144a9e1f7bbeed78e7079)
# - lib/openzeppelin-contracts-upgradeable: v5.3.0 (60b305a8f3ff0c7688f02ac470417b6bbf1c4d27)
# - lib/forge-std: v1.9.7 (77041d2ce690e692d6e03cc812b57d1ddaa4d505)
# To update: forge update <lib-name> or git submodule update --remote <path>

[fmt]
line_length = 100
tab_width = 4
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"

[rpc_endpoints]
oasys-testnet = "https://rpc.testnet.oasys.games"
oasys-mainnet = "https://rpc.mainnet.oasys.games"

[etherscan]
oasys-testnet = { chain_id = 9372, url = "https://explorer.testnet.oasys.games/api", key = "none" }
oasys-mainnet = { chain_id = 248, url = "https://explorer.oasys.games/api", key = "none" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
