[profile.default]
src = "contracts"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 200
ignored_error_codes = [2519,2018,5574,6321,8261]
fs_permissions = [
    { access = "read", path = "./script/templates/" },
    { access = "read-write", path = "./contracts/test-utils/deployers/" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
